### PR TITLE
fix: set stubsUnitByDefault for recursively generated mocks

### LINKED ISSUE #122: Automatically generated mock objects passed as constructor parameters of a mock don't get stubbed unit returning functions
Automatically mocked objects passed as constructor parameters of a mock don't get stubbed unit returning functions even though `stubsUnitByDefault` is `true`. Is this on purpose?

Given a mockable type *A* with a property of the mockable type *B*, `stubsUnitByDefault` is `true` for an object of type *A*, but  `false` for the object of type *B* passed to the constructor of type *A*.
The generated `mock()` function configures the mock itself (type *A*) setting `stubsUnitByDefault`, but the generated code for mock class *A* doesn't set `stubsUnitByDefault` for the mock object of type *B* passed to the constructor of type *A*. A `mock()` function for type *B* is not generated.

Below is a failing test for this scenario. I can open a PR with this code, if this is something that is supposed to work.

```kotlin
package io.github

import io.mockative.Mock
import io.mockative.classOf
import io.mockative.mock
import io.mockative.verify
import kotlin.test.Test

@Mockable
class MockWithNestedMockA(val nestedMock: NestedClass) {
    init {
        nestedMock.doSomethingReturnUnit()
    }
}

@Mockable
class NestedClass {
    fun doSomethingReturnUnit() {

    }
}

class MockWithNestedMockWithUnitReturningFunctionTests {
    @Mock
    val mockedObjectWithNestedMock = mock(classOf<MockWithNestedMockA>())

    @Test
    fun does_not_match_if_one_doesnt_match() {
        verify { mockedObjectWithNestedMock.nestedMock.doSomethingReturnUnit() }.wasInvoked(1)
    }
}

```

### PR DESCRIPTION
**Pull request by riQQ**
Add test to check recursive mock's stubsUnitByDefault behavior

Fixes #122

### CODE REVIEW

File: mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ClassName.Mockative.kt [hunk 1]
```diff
@@ -27,35 +27,35 @@ private fun mockValue(type: ClassName): CodeBlock {
...
+        DOUBLE_ARRAY -> Pair(false, CodeBlock.of("%T(0)", DOUBLE_ARRAY))
+        STRING -> Pair(false, CodeBlock.of("\"\""))
+        CHAR_SEQUENCE -> Pair(false, CodeBlock.of("\"\""))
+
+        ARRAY_LIST -> Pair(false, CodeBlock.of("%T()", ARRAY_LIST))
+        ARRAY_DEQUE -> Pair(false, CodeBlock.of("%T()", ARRAY_DEQUE))
+        LINKED_HASH_MAP -> Pair(false, CodeBlock.of("%T()", LINKED_HASH_MAP))
+        HASH_MAP -> Pair(false, CodeBlock.of("%T()", HASH_MAP))
+        LINKED_HASH_SET -> Pair(false, CodeBlock.of("%T()", LINKED_HASH_SET))
+        HASH_SET -> Pair(false, CodeBlock.of("%T()", HASH_SET))
```
Comment (kris098e) [inline mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ClassName.Mockative.kt:57]: Either add a function that returns a pair of fale to a provided codeblock like:
```kotlin
fun funName(isMock: Boolean = false, codeBlock: CodeBlock): Pair<Boolean, CodeBlock> = Pair(isMock, codeBlock)
```
And then call this, as having so many `false` statements is very error-prone. This also increases readability while also giving a name to the `Boolean`.

File: mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ProcessableType.KotlinPoet.kt [hunk 2]
```diff
@@ -171,7 +171,15 @@ internal fun ProcessableType.buildMockTypeSpec(): TypeSpec {
...
-                typeSpec.addSuperclassConstructorParameter("%L", valueOf(type))
+                val (isMock, codeBlock) = valueOf(type)
+                if (isMock)
+                    typeSpec.addSuperclassConstructorParameter(
+                        "%M(%L) { stubsUnitByDefault·=·%L }",
+                        CONFIGURE,
+                        codeBlock,
+                        stubsUnitByDefault)
+                else
+                    typeSpec.addSuperclassConstructorParameter("%L", codeBlock)
```
Comment (kris098e) [inline mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ProcessableType.KotlinPoet.kt:182]: This does not follow code structure of the project

```suggestion
                if (isMock) typeSpec.addSuperclassConstructorParameter(
                        "%M(%L) { stubsUnitByDefault·=·%L }",
                        CONFIGURE,
                        codeBlock,
                        stubsUnitByDefault
                   )
                else typeSpec.addSuperclassConstructorParameter("%L", codeBlock)
```

**Comment by kris098e** [comment]
You are very much welcome to not commit suggestions directly if you want full credit for the pr instead of having me as co-author :)

File: mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ClassName.Mockative.kt (hunk 1 above)
Comment (riQQ) [reply mockative-processor/src/main/kotlin/io/mockative/kotlinpoet/ClassName.Mockative.kt]: I refactored this to use a data class. I hope I understood you correctly.

**Comment by riQQ** [comment]
Sorry, I don't know why I didn't catch the tests failing. Should be fixed now.

File: shared/src/commonTest/kotlin/io/github/MockWithNestedMockWithUnitReturningFunctionTests.kt [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+        mockedClassWithProperty.propertyWithUnitReturningFunction.doSomethingReturnUnit()
+        verify { mockedClassWithProperty.propertyWithUnitReturningFunction.doSomethingReturnUnit() }.wasInvoked(1)
+    }
+
+    @Test
+    fun stubs_units_by_default_doesnt_affect_function_not_returning_unit() {
+        every { mockedClassWithProperty.propertyWithUnitReturningFunction }.returns(mockedClassUsedAsPropertyWithUnitReturningFunction)
+        assertFailsWith<MissingExpectationException> { mockedClassWithProperty.propertyWithUnitReturningFunction.returnSomeString() }
+    }
+}
```
Comment (kris098e) [inline shared/src/commonTest/kotlin/io/github/MockWithNestedMockWithUnitReturningFunctionTests.kt:29]: Hi @riQQ

Good work on the PR
However, I dont see how these tests asses that the added functionality works. 
Could you clarify what your thoughts are?

Comment (riQQ) [reply shared/src/commonTest/kotlin/io/github/MockWithNestedMockWithUnitReturningFunctionTests.kt:29]: @kris098e you're right, the tests don't work, because the property can't be accessed without mocking it, which overrides the actual value set via the constructor in the generated code. I don't know how to test this 'feature' and that makes me wonder if this feature really does anything.

```kotlin
public fun mock(@Suppress("UNUSED_PARAMETER") type: KClass<ClassUsedAsPropertyWithUnitReturningFunction>):
    ClassUsedAsPropertyWithUnitReturningFunction =
    configure(ClassUsedAsPropertyWithUnitReturningFunctionMock(null)) { stubsUnitByDefault = true }
```

Comment (kris098e) [reply shared/src/commonTest/kotlin/io/github/MockWithNestedMockWithUnitReturningFunctionTests.kt:29]: Yes, at the moment what is suggested does not work in Mockative.

We did however discuss implementing this. It should be done in a way where getting the properties that are mockative mocks should be returned if there are no stubbing for the getting the property. This is for instance in alignment with MockK.

This would allow to both have a fall back and also the ability to stub the getter if the user wants

---
Therefore what you have implemented here is very important for the project, if someone finds the time to implement the above specified feature.

But for now, we should drop the tests

Comment (riQQ) [reply shared/src/commonTest/kotlin/io/github/MockWithNestedMockWithUnitReturningFunctionTests.kt]: @kris098e done, tests removed

**Review by kris098e — APPROVED** [review]
