### PR TITLE
Fix trivial bugs

### LINKED ISSUE #73: Overload resolution ambiguity: `SuspendResultBuilder.invokes` and `ResultBuilder.invokes`
- Code (similar to readme.md), but it does not work :))
```kotlin
coEvery { repoItemApi.searchRepoItems(term, page) }
  .invokes { FAKE_REPO_ITEMS_SEARCH_RESPONSE.right() }
```

- Error
```
Overload resolution ambiguity. All these functions match.
public open fun invokes(block: suspend () → Either<Throwable, RepoItemsSearchResponse>): Unit defined in io.mockative.SuspendResultBuilder
public final fun invokes(block: suspend (arguments: Array<Any?>) → Either<Throwable, RepoItemsSearchResponse>): Unit defined in io.mockative.SuspendResultBuilder
```

- Currently, there are two `invokes` functions in `SuspendResultBuilder`:
   - `fun invokes(block: suspend (arguments: Array<Any?>) -> R)` (1).
   - `override fun invokes(block: suspend () -> R)` (2).

When we want to use (2), but (1) has higher priority, we have to use it like this `invokes { _ -> }`. Without `_ -> ` does not work.
IMO, could we provide (1) with another name to avoid the ambiguity? Maybe `invokesWithArgs` 😁.
`ResultBuilder` has the same thing.

Thank you so much 🙏

### LINKED ISSUE #97: Failure to get class name during code generation on some Android source sets
Starting on Mockative `2.2.0`, I'm facing this issue when running `kspDebugAndroidTestKotlinAndroid`.

My guess is that it was introduced in #94, as this same task was running successfully in our codebase during `2.1.0` and #94 seems to be the biggest change around this area since then.

```
> Task :logic:kspDebugAndroidTestKotlinAndroid FAILED
e: [ksp] java.lang.IllegalStateException: Required value was null.
	at com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
	at com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(KsClassDeclarations.kt:23)
	at io.mockative.ProcessableType$Companion.fromDeclaration(ProcessableType.kt:82)
	at io.mockative.ProcessableType$Companion.fromResolver(ProcessableType.kt:143)
	at io.mockative.MockativeSymbolProcessor.process(MockativeSymbolProcessor.kt:25)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
```

I am trying to get more information about it. I'm not sure what is the edge case I'm falling into at the moment, as it doesn't seem to have affected Mockative's `:shared:kspDebugAndroidTestKotlinAndroid` for example.

### LINKED ISSUE #98: Incorrect `MissingExpectationException` when switching Coroutine Context in iOS
This works on JVM and Android, but fails on iOS.

```kotlin
interface SomeInterface {
    suspend fun doThing()
}

@Mock
val mock = mock(SomeInterface::class)

@Test
fun givenItWasNotExplicitlyStubbed_whenInvoking_thenShouldReturnUnitByDefault() = runTest {
    coEvery { mock.doThing() }.returns(Unit)

    withContext(Dispatchers.Default) {
        mock.doThing()
    }
}
```

It struggles to find the expectation when calling from some other context on native.

----

If setting the expectation within the context, it works:

```kotlin

@Test
fun givenItWasNotExplicitlyStubbed_whenInvoking_thenShouldReturnUnitByDefault() = runTest {
    coEvery { mock.doThing() }.returns(Unit)

    withContext(Dispatchers.Default) {
        coEvery { mock.doThing().returns(Unit)

        mock.doThing()
    }
}
```

### PR DESCRIPTION
**Pull request by Nillerr**
- **Fixes #73 by removing unnecessary invoke functions**
- **Fixes #98 by making mockable map non-thread-local**
- **Fixes #97 by adding proper error message for lack of types**

### CODE REVIEW

File: mockative/src/commonMain/kotlin/io/mockative/ResultBuilder.kt [hunk 1]
```diff
@@ -12,7 +12,13 @@ class ResultBuilder<R>(
         mock.addBlockingStub(ClosedBlockingStub(expectation, blocks))
     }
 
-    override fun invokes(block: () -> R) = invokes { _ -> block() }
+    fun returns(value: R) = invokes { value }
 
-    override fun invokesMany(vararg blocks: () -> R) = invokesMany(blocks.map { block -> { _ -> block() } })
```
Comment (TWiStErRob) [inline mockative/src/commonMain/kotlin/io/mockative/ResultBuilder.kt:17]: What is the reasoning behind removing the vararg variant?

1. It's a breaking change in a **patch** version
2. Without the vararg, every use site has to do a `listOf(...)` or create a helper function to polyfill the existing method.

You can see an example failure here:

https://github.com/TWiStErRob/net.twisterrob.travel/pull/207#issuecomment-2132321041

and an example fix:

https://github.com/TWiStErRob/net.twisterrob.travel/pull/207/commits/e294dfa5111ef9cae9ab818b4cd29d737b12caa4

I'm only using this in a single class, imagine a project that fully relies on this...

Comment (Nillerr) [reply mockative/src/commonMain/kotlin/io/mockative/ResultBuilder.kt:17]: Good point @TWiStErRob! I guess I imagined nobody actually used this function since I personally didn't think it was that useful. I'll add it back in and release a hotfix for it in `v2.2.2` shortly, and be more careful of retaining backward compatibility going forward, making sure to use `@Deprecated` warnings for future occurrences.

Comment (TWiStErRob) [reply mockative/src/commonMain/kotlin/io/mockative/ResultBuilder.kt:17]: No worries.

Tip: write tests for these methods and it'll show you when they're useful, and whether the DX of them is good :)
